[package]
edition = "2021"
name = "stat_client"
version = "1.7.2"

rust-version = "1.69"

authors = ["doge <doge.py@gmail.com>"]
categories = ["monitoring-tools"]
description = "A simple server monitoring tool"
keywords = ["devops", "notifications", "monitoring", "dashboard", "alerting"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/zdz/ServerStatus-Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
chrono = "0.4"

[dependencies]
anyhow = "1"
bytes = {version = "1", features = ["serde"]}
chrono = "0.4"
clap = {version = "4.3", features = ["derive", "unicode", "env"]}
fastrand = "1.9.0"
hyper = {version = "0.14", features = ["full"]}
lazy_static = "1.4"
log = "0.4"
once_cell = "1"
pretty_env_logger = "0.5"
prost = "0.11"
regex = "1.8"
reqwest = {version = "0.11", features = ["json", "rustls-tls", "brotli", "gzip", "deflate", "stream", "socks"], default-features = false}
serde = {version = "1.0", default-features = false, features = ["derive", "alloc"]}
serde_json = {version = "1.0", default-features = false, features = ["alloc"]}
stat_common = {path = "../common"}
sysinfo = "0.29.0"
tokio = {version = "1", features = ["full"]}
tonic = {version = "0.9", features = ["tls"]}
tower = { version = "0.4" }
md5 = "0.7.0"

[features]
default = ["sysinfo"]
native = []
sysinfo = []
